require_relative '../lib/game'
require_relative '../lib/view'
require_relative '../lib/code_generator'
require_relative '../lib/guess_validator'
require_relative '../lib/player'
require_relative '../lib/rules'